cameras:
- enabled: true
  id: imou_01
  name: IMOU 
  url: "rtsp://admin:L26F76F1@192.168.1.29:554/cam/realmonitor?channel=1&subtype=1"
  zones:
    restricted_zones:
    - active_hours: 00:00-06:00,18:00-23:59
      name: Zone interdite 1
      points:
      - - 0.1
        - 0.1
      - - 0.4
        - 0.1
      - - 0.4
        - 0.5
      - - 0.1
        - 0.5
# - enabled: true
#   id: imou_02
#   name: '2'
#   url: rtsp://admin:L2C97D4B@192.168.1.48:554/cam/realmonitor?channel=1&subtype=0
#   zones:
#     restricted_zones:
#     - active_hours: 00:00-23:59
#       name: Zone surveillée 2
#       points:
#       - - 0.2
#         - 0.2
#       - - 0.8
#         - 0.2
#       - - 0.8
#         - 0.8
#       - - 0.2
#         - 0.8
# - enabled: true
#   id: imou_03
#   name: Caméra IMOU ranger 2C H3 0614
#   url: rtsp://admin:L2D0488D@192.168.1.50:554/cam/realmonitor?channel=1&subtype=0
#   zones:
#     restricted_zones:
#     - active_hours: 00:00-23:59
#       name: Zone surveillance 3
#       points:
#       - - 0.15
#         - 0.15
#       - - 0.85
#         - 0.15
#       - - 0.85
#         - 0.85
#       - - 0.15
#         - 0.85
# - enabled: true
#   id: imou_04
#   name: Caméra IMOU 2C H3 9AC7
#   url: rtsp://admin:L2D2D121@192.168.1.49:554/cam/realmonitor?channel=1&subtype=0
#   zones:
#     restricted_zones:
#     - active_hours: 00:00-23:59
#       name: Zone surveillance 4
#       points:
#       - - 0.15
#         - 0.15
#       - - 0.85
#         - 0.15
#       - - 0.85
#         - 0.85
#       - - 0.15
#         - 0.85
